class Prescription < ApplicationRecord
  belongs_to :profile
  belongs_to :provider
  validates_presence_of :name, :dose, :dose_units, on: :create

  enum dose_units: [
        "%",
        "AU",
        "AU/mL",
        "bar",
        "BAU",
        "BAU/mL",
        "bead",
        "BU",
        "capsule",
        "CCID_50",
        "cellular sheet",
        "Ci",
        "cloth",
        "cm^2",
        "D'ag'U",
        "disc",
        "dL",
        "douche",
        "drops",
        "FFU",
        "g",
        "globule",
        "granule",
        "gum",
        "hp_C",
        "hp_M",
        "hp_Q",
        "hp_X",
        "IU",
        "IU/L",
        "IU/mL",
        "kp_C",
        "L",
        "Lf",
        "LfU/mL",
        "lozenge",
        "mCi",
        "mCi/mL",
        "mEq",
        "mg",
        "mg/actuat",
        "mg/hr",
        "mg/mg",
        "mg/mL",
        "mL",
        "mmol",
        "mol",
        "mU",
        "ng",
        "nmol",
        "organisms",
        "pastille",
        "patch",
        "pellet",
        "PFU",
        "pill",
        "PNU",
        "PNU/mL",
        "pouch",
        "puff",
        "ring",
        "salve",
        "stick",
        "strip",
        "suppository",
        "swab",
        "tablet",
        "tampon",
        "tape",
        "tbsp",
        "TCID_50",
        "tsp",
        "U",
        "uCi",
        "ug",
        "ug/mL",
        "uL",
        "umol",
        "unt",
        "unt/mL",
        "USP'U",
        "vial",
        "wafer",
        "X"
    ]

  def provider
    Provider.find(self.provider_id)
  end

end
